// native/inline-wasm.mjs — copies the WebAssembly engine into the Lab.
//
// native/build-wasm.sh compiles the engine (native/lgca_engine.*, native/wasm/lgca_wasm.cpp)
// into one JavaScript file, native/build/lgca_wasm.js: Emscripten's loader ("glue") with the
// compiled engine inside it as base64 text. This script writes that file, unchanged, into
// lgca-viz/lgca-lab.html as the text of a block
//
//   <script id="wasmEngine" type="text/plain"> ... </script>
//
// placed right after the worker block (<script id="workerSrc">). The browser does not run
// a text/plain block; the Lab's worker evaluates its text when the WebAssembly engine is
// chosen. So the Lab stays one file that opens directly in a browser, with nothing fetched.
//
// That block is a build output: never edit it by hand. After any change to the engine,
//   bash native/build-wasm.sh && node native/inline-wasm.mjs
// then run the checks (cd lgca-viz && node verify-parity.mjs && node verify-parity-wasm.mjs).
// Nothing else in the HTML file changes; the JavaScript engine (<script id="engineSrc">) and
// the worker block are checked to be byte for byte as they were.
//
//   node native/inline-wasm.mjs [glue.js [lab.html]]   write (or replace) the block
//   node native/inline-wasm.mjs --check [...]          exit 1 if the block is not the glue

import {createHash} from "node:crypto";
import {readFileSync, renameSync, writeFileSync} from "node:fs";
import {dirname, join, relative} from "node:path";
import {fileURLToPath} from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const checkOnly = args[0] === "--check";
if (checkOnly) args.shift();
const gluePath = args[0] ?? join(root, "native", "build", "lgca_wasm.js");
const labPath = args[1] ?? join(root, "lgca-viz", "lgca-lab.html");

const fail = message => { console.error(`inline-wasm: ${message}`); process.exit(1); };

// The generated block: a comment saying where it comes from, then the script element. The
// text sits between two newlines, which the Lab and the checks strip (exactly one each).
const OPEN = '<script id="wasmEngine" type="text/plain">';
const BLOCK = /<!-- wasmEngine: generated by native\/inline-wasm\.mjs[\s\S]*?-->\n<script id="wasmEngine" type="text\/plain">\n[\s\S]*?\n<\/script>/;

function sha256(text) { return createHash("sha256").update(text).digest("hex"); }

// The size and sha256 are those of the glue file itself (as `shasum -a 256` gives them).
function blockFor(glue, fileText, source) {
  return `<!-- wasmEngine: generated by native/inline-wasm.mjs from ${source}\n` +
    `     (${Buffer.byteLength(fileText)} bytes, sha256 ${sha256(fileText)}).\n` +
    "     A build output: do not edit by hand. To rebuild after an engine change:\n" +
    "     bash native/build-wasm.sh && node native/inline-wasm.mjs -->\n" +
    `${OPEN}\n${glue}\n</script>`;
}

// The text of a <script id="..."> block (null if absent), for the before/after comparison.
function scriptText(html, id) {
  const start = html.indexOf(`<script id="${id}"`);
  if (start < 0) return null;
  const end = html.indexOf("</script>", start);
  return end < 0 ? null : html.slice(start, end);
}

const fileText = readFileSync(gluePath, "utf8");
// The block holds the file without its last newline, and the checks (verify-parity-wasm.mjs)
// add that newline back before comparing size and sha256; so the file must end in one.
if (!fileText.endsWith("\n")) fail(`${gluePath} does not end with a newline (Emscripten's output does)`);
const glue = fileText.slice(0, -1);
const html = readFileSync(labPath, "utf8");

// The glue must survive the HTML parser unchanged. Inside a script element the parser only
// looks for "</script" (which would end the block) and, after "<!--", for "<script" (which
// changes how "</script" is read); it also turns CR and CR LF into LF and refuses NUL. The
// glue is plain ASCII without any of these; refuse to inline one that is not.
if (/<\/script|<!--|<script/i.test(glue)) fail(`${gluePath} contains "</script", "<!--" or "<script"; it cannot be inlined`);
if (/[^\x09\x0a\x20-\x7e]/.test(glue)) fail(`${gluePath} contains characters other than printable ASCII, tab and newline`);
if (!glue.includes("createLgcaWasm")) fail(`${gluePath} does not define createLgcaWasm: not the engine's glue?`);

const source = relative(root, gluePath).split("\\").join("/");
const block = blockFor(glue, fileText, source);
const current = html.match(BLOCK);

if (checkOnly) {
  const text = current && current[0].slice(current[0].indexOf(OPEN) + OPEN.length + 1, -"\n</script>".length);
  if (text === glue) { console.log(`inline-wasm: the Lab's wasmEngine block is ${source} (sha256 ${sha256(fileText)})`); process.exit(0); }
  fail(current ? `the Lab's wasmEngine block differs from ${source}; rebuild it with node native/inline-wasm.mjs`
               : "the Lab has no wasmEngine block");
}

let updated;
if (current) {
  updated = html.replace(BLOCK, () => block);          // a function: "$" in the glue stays literal
} else {
  if (html.includes(OPEN)) fail("the Lab has a wasmEngine block without its generated comment; remove it by hand first");
  const workerStart = html.indexOf('<script id="workerSrc">');
  const workerEnd = workerStart < 0 ? -1 : html.indexOf("</script>", workerStart);
  if (workerEnd < 0) fail('no <script id="workerSrc"> block in the Lab');
  const at = workerEnd + "</script>".length;
  updated = html.slice(0, at) + "\n\n" + block + html.slice(at);
}

// The engine and worker blocks must be as they were, and the new block must read back as
// the glue; otherwise nothing is written.
for (const id of ["engineSrc", "workerSrc"])
  if (scriptText(updated, id) !== scriptText(html, id)) fail(`the ${id} block would change; nothing written`);
const written = updated.match(BLOCK)?.[0];
if (!written || written.slice(written.indexOf(OPEN) + OPEN.length + 1, -"\n</script>".length) !== glue)
  fail("the written block would not read back as the glue; nothing written");

if (updated === html) {
  console.log(`inline-wasm: ${relative(root, labPath)} already holds ${source} (sha256 ${sha256(fileText)}); unchanged`);
} else {
  const temp = `${labPath}.inline-wasm.tmp`;
  writeFileSync(temp, updated);
  renameSync(temp, labPath);
  console.log(`inline-wasm: wrote ${source} (${Buffer.byteLength(fileText)} bytes, sha256 ${sha256(fileText)}) into ` +
    `${relative(root, labPath)} (${Buffer.byteLength(html)} -> ${Buffer.byteLength(updated)} bytes)`);
}
